### ISSUE TITLE
 ValueError: invalid literal for int() with base 10: 'post20170921'

### ISSUE THREAD

**Issue by Netherdrake** [ludbb/secp256k1-py#23]
OS: Arch Linux
Python: Python 3.6.3 (Anaconda)

```
Collecting secp256k1 (from ethereum<2.0.0,>=1.6.1->eth-testrpc>=1.3.0->populus)
  Using cached secp256k1-0.13.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7b11re3w/secp256k1/setup.py", line 41, in <module>
        if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
      File "/tmp/pip-build-7b11re3w/secp256k1/setup.py", line 41, in <listcomp>
        if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
    ValueError: invalid literal for int() with base 10: 'post20170921'
```

**Comment by zzir** [comment]
Solved it? I also encountered this problem.

**Comment by zzir** [comment]
edit setup.py:
```
# We require setuptools >= 3.3
if [int(i) for i in setuptools_version.split('.', 2)[:2]] < [3, 3]:
    raise SystemExit(
        'Your setuptools version ({}) is too old to correctly install this '
        'package. Please upgrade to a newer version (>= 3.3).'.format(setuptools_version)
    )
```

**Comment by zzir** [comment]
```bash
pip install setup.py --upgrade
```

**Comment by zzir** [comment]
```
apk add autoconf py3-cffi abuild libtool automake make gcc musl-dev python3-dev
pip3 install setuptools --upgrade
pip3 install secp256k1
```

**Comment by nandubatchu** [comment]
This is failing in MacOS also:

```ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3l/sccw9xm565s1xv0ynvcz4jvw0000gp/T/pip-install-rd95tr8j/secp256k1/setup.py", line 41, in <module>
        if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
      File "/private/var/folders/3l/sccw9xm565s1xv0ynvcz4jvw0000gp/T/pip-install-rd95tr8j/secp256k1/setup.py", line 41, in <listcomp>
        if [int(i) for i in setuptools_version.split('.')] < [3, 3]:
    ValueError: invalid literal for int() with base 10: 'post20201221'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3l/sccw9xm565s1xv0ynvcz4jvw0000gp/T/pip-install-rd95tr8j/secp256k1/```
