### ISSUE TITLE
No module named \'secp256k1._libsecp256k1\

### ISSUE THREAD

**Issue by JackPickering** [ludbb/secp256k1-py#26]
I am currently trying to run this module on a Debian server running node.js, which then spins up a python3 process in order to run various tasks. Whenever I use this module, I get the error:
`No module named \'secp256k1._libsecp256k1\
`

I have installed it in experimental mode
I have the latest C compiler
I have installed the relevant packages:
build-essential
automake
pkg-config
libtool
libffi-dev
libgmp-dev

The error comes from the line 5 in _init_.py:
` from ._libsecp256k1 import ffi, lib`

When trying to run pip3 install --no-binary libsecp256k1 I get:

```
`Usage:
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-binary`
```

```
staging >     ----- Python Traceback -----                                                                                                                   
staging >     File "ecdsa_imp/lib/python3.6/site-packages/ecdsa.py", line 6, in <module> 
staging >       from sign import sign                                                                                                                         
staging >     File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/sign.py", line 8, in <module>                                           
staging >       from secp256k1 import PrivateKey                                                                                                              
staging >     File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/secp256k1/__init__.py", line 5, in <module>                             
staging >       from ._libsecp256k1 import ffi, lib                                                                                                            
staging >   traceback: 'Traceback (most recent call last):\n  File "ecdsa_imp/lib/python3.6/site-packages/ecdsa.py", line 6, in <module>\n    from sign import sign\n  File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/sign.py", line 8, in <module>\n    from secp256k1 import PrivateKey\n  File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/secp256k1/__init__.py", line 5, in <module>\n    from ._libsecp256k1 import ffi, lib\nImportError : No module named \'secp256k1._libsecp256k1\'\n',                                                                                                                  
staging >   executable: '/usr/bin/python3',
```

Is there anything else that I am missing?

**Comment by JackPickering** [comment]
It turned out there was an issue with the bindings between our python-shell and our underlying OS.
