### ISSUE TITLE
Some tests fail on FreeBSD (in the port)

### ISSUE THREAD

**Issue by yurivict** [ludbb/secp256k1-py#31]
```
== CPU count: 8
Run tests sequentially
0:00:00 load avg: 0.35 [  1/403] test_grammar
0:00:00 load avg: 0.35 [  2/403] test_opcodes
0:00:00 load avg: 0.35 [  3/403] test_dict
0:00:00 load avg: 0.35 [  4/403] test_builtin
0:00:00 load avg: 0.35 [  5/403] test_exceptions
0:00:00 load avg: 0.35 [  6/403] test_types
0:00:00 load avg: 0.35 [  7/403] test_unittest
0:00:00 load avg: 0.35 [  8/403] test_doctest
0:00:00 load avg: 0.35 [  9/403] test_doctest2
0:00:00 load avg: 0.35 [ 10/403] test_MimeWriter
0:00:00 load avg: 0.35 [ 11/403] test_SimpleHTTPServer
0:00:00 load avg: 0.35 [ 12/403] test_StringIO
0:00:01 load avg: 0.35 [ 13/403] test___all__
0:00:02 load avg: 0.35 [ 14/403] test___future__
0:00:02 load avg: 0.35 [ 15/403] test__locale
0:00:02 load avg: 0.35 [ 16/403] test__osx_support
0:00:02 load avg: 0.35 [ 17/403] test_abc
0:00:02 load avg: 0.35 [ 18/403] test_abstract_numbers
0:00:02 load avg: 0.35 [ 19/403] test_aepack
test_aepack skipped -- No module named aetypes
0:00:02 load avg: 0.35 [ 20/403] test_aifc -- test_aepack skipped
0:00:02 load avg: 0.35 [ 21/403] test_al
test_al skipped -- No module named al
0:00:02 load avg: 0.35 [ 22/403] test_anydbm -- test_al skipped
0:00:02 load avg: 0.35 [ 23/403] test_applesingle
test_applesingle skipped -- No module named MacOS
0:00:02 load avg: 0.35 [ 24/403] test_argparse -- test_applesingle skipped
0:00:04 load avg: 0.40 [ 25/403] test_array
0:00:04 load avg: 0.40 [ 26/403] test_ascii_formatd
0:00:04 load avg: 0.40 [ 27/403] test_ast
0:00:04 load avg: 0.40 [ 28/403] test_asynchat
0:00:09 load avg: 0.37 [ 29/403] test_asyncore
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/test/test_asyncore.py", line 728, in <lambda>
    t = threading.Thread(target=lambda: asyncore.loop(timeout=0.1, count=500))
  File "/usr/local/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')

0:00:12 load avg: 0.34 [ 30/403] test_atexit
0:00:12 load avg: 0.34 [ 31/403] test_audioop
0:00:12 load avg: 0.34 [ 32/403] test_augassign
0:00:12 load avg: 0.34 [ 33/403] test_base64
0:00:12 load avg: 0.34 [ 34/403] test_bastion
0:00:12 load avg: 0.34 [ 35/403] test_bigaddrspace
0:00:12 load avg: 0.34 [ 36/403] test_bigmem
0:00:13 load avg: 0.34 [ 37/403] test_binascii
0:00:13 load avg: 0.34 [ 38/403] test_binhex
0:00:13 load avg: 0.34 [ 39/403] test_binop
0:00:13 load avg: 0.34 [ 40/403] test_bisect
0:00:13 load avg: 0.34 [ 41/403] test_bool
0:00:13 load avg: 0.34 [ 42/403] test_bsddb
test_bsddb skipped -- No module named _bsddb
0:00:13 load avg: 0.34 [ 43/403] test_bsddb185 -- test_bsddb skipped
0:00:13 load avg: 0.34 [ 44/403] test_bsddb3
test_bsddb3 skipped -- No module named _bsddb
0:00:13 load avg: 0.34 [ 45/403] test_buffer -- test_bsddb3 skipped
0:00:13 load avg: 0.34 [ 46/403] test_bufio
0:00:14 load avg: 0.34 [ 47/403] test_bytes
0:00:15 load avg: 0.34 [ 48/403] test_bz2
0:00:16 load avg: 0.34 [ 49/403] test_calendar
0:00:17 load avg: 0.39 [ 50/403] test_call
0:00:17 load avg: 0.39 [ 51/403] test_capi
0:00:20 load avg: 0.39 [ 52/403] test_cd
test_cd skipped -- No module named cd
0:00:20 load avg: 0.39 [ 53/403] test_cfgparser -- test_cd skipped
0:00:20 load avg: 0.39 [ 54/403] test_cgi
0:00:20 load avg: 0.39 [ 55/403] test_charmapcodec
0:00:21 load avg: 0.39 [ 56/403] test_cl
test_cl skipped -- No module named cl
0:00:21 load avg: 0.39 [ 57/403] test_class -- test_cl skipped
0:00:21 load avg: 0.39 [ 58/403] test_cmath
0:00:21 load avg: 0.39 [ 59/403] test_cmd
0:00:21 load avg: 0.39 [ 60/403] test_cmd_line
0:00:21 load avg: 0.39 [ 61/403] test_cmd_line_script
0:00:22 load avg: 0.44 [ 62/403] test_code
0:00:22 load avg: 0.44 [ 63/403] test_codeccallbacks
0:00:22 load avg: 0.44 [ 64/403] test_codecencodings_cn
0:00:22 load avg: 0.44 [ 65/403] test_codecencodings_hk
0:00:22 load avg: 0.44 [ 66/403] test_codecencodings_iso2022
0:00:23 load avg: 0.44 [ 67/403] test_codecencodings_jp
0:00:24 load avg: 0.44 [ 68/403] test_codecencodings_kr
0:00:24 load avg: 0.44 [ 69/403] test_codecencodings_tw
0:00:24 load avg: 0.44 [ 70/403] test_codecmaps_cn
test_codecmaps_cn skipped -- Use of the `urlfetch' resource not enabled
0:00:24 load avg: 0.44 [ 71/403] test_codecmaps_hk -- test_codecmaps_cn skipped (resource denied)
test_codecmaps_hk skipped -- Use of the `urlfetch' resource not enabled
0:00:25 load avg: 0.44 [ 72/403] test_codecmaps_jp -- test_codecmaps_hk skipped (resource denied)
test_codecmaps_jp skipped -- Use of the `urlfetch' resource not enabled
0:00:25 load avg: 0.44 [ 73/403] test_codecmaps_kr -- test_codecmaps_jp skipped (resource denied)
test_codecmaps_kr skipped -- Use of the `urlfetch' resource not enabled
0:00:25 load avg: 0.44 [ 74/403] test_codecmaps_tw -- test_codecmaps_kr skipped (resource denied)
test_codecmaps_tw skipped -- Use of the `urlfetch' resource not enabled
0:00:25 load avg: 0.44 [ 75/403] test_codecs -- test_codecmaps_tw skipped (resource denied)
0:00:26 load avg: 0.44 [ 76/403] test_codeop
0:00:26 load avg: 0.44 [ 77/403] test_coercion
0:00:26 load avg: 0.44 [ 78/403] test_collections
0:00:27 load avg: 0.44 [ 79/403] test_colorsys
0:00:27 load avg: 0.49 [ 80/403] test_commands
0:00:27 load avg: 0.49 [ 81/403] test_compare
0:00:27 load avg: 0.49 [ 82/403] test_compile
0:00:27 load avg: 0.49 [ 83/403] test_compileall
0:00:27 load avg: 0.49 [ 84/403] test_compiler
0:00:27 load avg: 0.49 [ 85/403] test_complex
0:00:28 load avg: 0.49 [ 86/403] test_complex_args
0:00:28 load avg: 0.49 [ 87/403] test_contains
0:00:28 load avg: 0.49 [ 88/403] test_contextlib
0:00:28 load avg: 0.49 [ 89/403] test_cookie
0:00:28 load avg: 0.49 [ 90/403] test_cookielib
0:00:28 load avg: 0.49 [ 91/403] test_copy
0:00:28 load avg: 0.49 [ 92/403] test_copy_reg
0:00:28 load avg: 0.49 [ 93/403] test_cpickle
0:00:30 load avg: 0.49 [ 94/403] test_cprofile
0:00:30 load avg: 0.49 [ 95/403] test_crypt
0:00:30 load avg: 0.49 [ 96/403] test_csv
0:00:30 load avg: 0.49 [ 97/403] test_ctypes
0:00:32 load avg: 0.49 [ 98/403] test_curses
test_curses skipped -- Use of the `curses' resource not enabled
0:00:32 load avg: 0.49 [ 99/403] test_datetime -- test_curses skipped (resource denied)
0:00:33 load avg: 0.45 [100/403] test_dbm
0:00:33 load avg: 0.45 [101/403] test_decimal
0:00:34 load avg: 0.45 [102/403] test_decorators
0:00:34 load avg: 0.45 [103/403] test_defaultdict
0:00:34 load avg: 0.45 [104/403] test_deque
0:00:37 load avg: 0.45 [105/403] test_descr
0:00:38 load avg: 0.49 [106/403] test_descrtut
0:00:38 load avg: 0.49 [107/403] test_dictcomps
0:00:38 load avg: 0.49 [108/403] test_dictviews
0:00:38 load avg: 0.49 [109/403] test_difflib
0:00:39 load avg: 0.49 [110/403] test_dircache
0:00:40 load avg: 0.49 [111/403] test_dis
0:00:41 load avg: 0.49 [112/403] test_distutils
0:00:42 load avg: 0.49 [113/403] test_dl
test_dl skipped -- No module named dl
0:00:42 load avg: 0.49 [114/403] test_docxmlrpc -- test_dl skipped
0:00:45 load avg: 0.45 [115/403] test_dumbdbm
0:00:45 load avg: 0.45 [116/403] test_dummy_thread
0:00:45 load avg: 0.45 [117/403] test_dummy_threading
0:00:45 load avg: 0.45 [118/403] test_email
0:00:49 load avg: 0.74 [119/403] test_email_codecs
0:00:49 load avg: 0.74 [120/403] test_email_renamed
0:00:49 load avg: 0.74 [121/403] test_ensurepip
0:00:49 load avg: 0.74 [122/403] test_enumerate
0:00:49 load avg: 0.74 [123/403] test_eof
0:00:49 load avg: 0.74 [124/403] test_epoll
test_epoll skipped -- test works only on Linux 2.6
0:00:49 load avg: 0.74 [125/403] test_errno -- test_epoll skipped
0:00:49 load avg: 0.74 [126/403] test_exception_variations
0:00:50 load avg: 0.74 [127/403] test_extcall
0:00:50 load avg: 0.74 [128/403] test_fcntl
0:00:50 load avg: 0.74 [129/403] test_file
0:00:50 load avg: 0.74 [130/403] test_file2k
0:00:57 load avg: 0.76 [131/403] test_file_eintr
0:00:58 load avg: 0.78 [132/403] test_filecmp
0:00:58 load avg: 0.78 [133/403] test_fileinput
0:00:58 load avg: 0.78 [134/403] test_fileio
0:00:58 load avg: 0.78 [135/403] test_float
0:00:59 load avg: 0.78 [136/403] test_fnmatch
0:00:59 load avg: 0.78 [137/403] test_fork1
0:01:04 load avg: 0.71 [138/403] test_format
0:01:04 load avg: 0.71 [139/403] test_fpformat
0:01:05 load avg: 0.71 [140/403] test_fractions
0:01:05 load avg: 0.71 [141/403] test_frozen
0:01:05 load avg: 0.71 [142/403] test_ftplib
0:01:09 load avg: 0.66 [143/403] test_funcattrs
0:01:09 load avg: 0.66 [144/403] test_functools
0:01:09 load avg: 0.66 [145/403] test_future
0:01:09 load avg: 0.66 [146/403] test_future3
0:01:09 load avg: 0.66 [147/403] test_future4
0:01:09 load avg: 0.66 [148/403] test_future5
0:01:09 load avg: 0.66 [149/403] test_future_builtins
0:01:09 load avg: 0.66 [150/403] test_gc
0:01:12 load avg: 0.66 [151/403] test_gdb
test_gdb skipped -- test_gdb only works on source builds at the moment.
0:01:12 load avg: 0.66 [152/403] test_gdbm -- test_gdb skipped
test_gdbm skipped -- No module named gdbm
0:01:12 load avg: 0.68 [153/403] test_generators -- test_gdbm skipped
0:01:12 load avg: 0.68 [154/403] test_genericpath
0:01:12 load avg: 0.68 [155/403] test_genexps
0:01:13 load avg: 0.68 [156/403] test_getargs
0:01:13 load avg: 0.68 [157/403] test_getargs2
0:01:13 load avg: 0.68 [158/403] test_getopt
0:01:13 load avg: 0.68 [159/403] test_gettext
0:01:13 load avg: 0.68 [160/403] test_gl
test_gl skipped -- No module named gl
0:01:13 load avg: 0.68 [161/403] test_glob -- test_gl skipped
0:01:13 load avg: 0.68 [162/403] test_global
0:01:13 load avg: 0.68 [163/403] test_grp
0:01:13 load avg: 0.68 [164/403] test_gzip
0:01:13 load avg: 0.68 [165/403] test_hash
0:01:14 load avg: 0.68 [166/403] test_hashlib
0:01:14 load avg: 0.68 [167/403] test_heapq
0:01:15 load avg: 0.68 [168/403] test_hmac
0:01:15 load avg: 0.68 [169/403] test_hotshot
0:01:15 load avg: 0.68 [170/403] test_htmllib
0:01:15 load avg: 0.68 [171/403] test_htmlparser
0:01:15 load avg: 0.68 [172/403] test_httplib
0:01:16 load avg: 0.68 [173/403] test_httpservers
0:01:18 load avg: 0.63 [174/403] test_idle
0:01:18 load avg: 0.63 [175/403] test_imageop
test_imageop skipped -- No module named imageop
0:01:18 load avg: 0.63 [176/403] test_imaplib -- test_imageop skipped
0:01:18 load avg: 0.63 [177/403] test_imgfile
test_imgfile skipped -- No module named imgfile
0:01:18 load avg: 0.63 [178/403] test_imghdr -- test_imgfile skipped
0:01:18 load avg: 0.63 [179/403] test_imp
0:01:18 load avg: 0.63 [180/403] test_import
0:01:19 load avg: 0.63 [181/403] test_import_magic
0:01:19 load avg: 0.63 [182/403] test_importhooks
0:01:19 load avg: 0.63 [183/403] test_importlib
0:01:19 load avg: 0.63 [184/403] test_index
0:01:19 load avg: 0.63 [185/403] test_inspect
0:01:19 load avg: 0.63 [186/403] test_int
0:01:20 load avg: 0.63 [187/403] test_int_literal
0:01:20 load avg: 0.63 [188/403] test_io
0:01:58 load avg: 0.78 [189/403] test_ioctl -- test_io passed in 37 sec
0:01:58 load avg: 0.78 [190/403] test_isinstance
0:01:58 load avg: 0.78 [191/403] test_iter
0:01:58 load avg: 0.78 [192/403] test_iterlen
0:01:58 load avg: 0.78 [193/403] test_itertools
0:02:03 load avg: 0.88 [194/403] test_json
0:02:05 load avg: 0.88 [195/403] test_kqueue
0:02:05 load avg: 0.88 [196/403] test_largefile
0:02:05 load avg: 0.88 [197/403] test_lib2to3
0:02:26 load avg: 0.99 [198/403] test_linecache
0:02:26 load avg: 0.99 [199/403] test_linuxaudiodev
test_linuxaudiodev skipped -- Use of the `audio' resource not enabled
0:02:27 load avg: 0.99 [200/403] test_list -- test_linuxaudiodev skipped (resource denied)
0:02:27 load avg: 0.99 [201/403] test_locale
0:02:27 load avg: 0.99 [202/403] test_logging
0:02:38 load avg: 0.91 [203/403] test_long
0:02:40 load avg: 0.91 [204/403] test_long_future
0:02:42 load avg: 0.91 [205/403] test_longexp
0:02:42 load avg: 0.92 [206/403] test_macos
test_macos skipped -- No module named MacOS
0:02:42 load avg: 0.92 [207/403] test_macostools -- test_macos skipped
test_macostools skipped -- No module named MacOS
0:02:42 load avg: 0.92 [208/403] test_macpath -- test_macostools skipped
0:02:42 load avg: 0.92 [209/403] test_macurl2path
0:02:42 load avg: 0.92 [210/403] test_mailbox
0:02:43 load avg: 0.92 [211/403] test_marshal
0:02:43 load avg: 0.92 [212/403] test_math
0:02:45 load avg: 0.92 [213/403] test_md5
0:02:45 load avg: 0.92 [214/403] test_memoryio
0:02:45 load avg: 0.92 [215/403] test_memoryview
0:02:45 load avg: 0.92 [216/403] test_mhlib
0:02:45 load avg: 0.92 [217/403] test_mimetools
0:02:45 load avg: 0.92 [218/403] test_mimetypes
0:02:46 load avg: 0.92 [219/403] test_minidom
0:02:46 load avg: 0.92 [220/403] test_mmap
0:02:46 load avg: 0.92 [221/403] test_module
0:02:46 load avg: 0.92 [222/403] test_modulefinder
0:02:46 load avg: 0.92 [223/403] test_msilib
test_msilib skipped -- No module named msilib
0:02:47 load avg: 0.92 [224/403] test_multibytecodec -- test_msilib skipped
0:02:48 load avg: 0.92 [225/403] test_multifile
0:02:48 load avg: 0.92 [226/403] test_multiprocessing
Process Process-16:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/test/test_multiprocessing.py", line 1774, in _writefd
    fd = reduction.recv_handle(conn)
  File "/usr/local/lib/python2.7/multiprocessing/reduction.py", line 83, in recv_handle
    return _multiprocessing.recvfd(conn.fileno())
RuntimeError: No file descriptor received
Process Process-17:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/test/test_multiprocessing.py", line 1774, in _writefd
    fd = reduction.recv_handle(conn)
  File "/usr/local/lib/python2.7/multiprocessing/reduction.py", line 83, in recv_handle
    return _multiprocessing.recvfd(conn.fileno())
RuntimeError: No file descriptor received
test test_multiprocessing failed -- multiple errors occurred; run in verbose mode for details
0:03:16 load avg: 0.80 [227/403/1] test_mutants -- test_multiprocessing failed
0:03:16 load avg: 0.80 [228/403/1] test_mutex
0:03:17 load avg: 0.80 [229/403/1] test_netrc
0:03:17 load avg: 0.80 [230/403/1] test_new
0:03:17 load avg: 0.80 [231/403/1] test_nis
0:03:17 load avg: 0.82 [232/403/1] test_nntplib
0:03:17 load avg: 0.82 [233/403/1] test_normalization
0:03:17 load avg: 0.82 [234/403/1] test_ntpath
0:03:17 load avg: 0.82 [235/403/1] test_old_mailbox
0:03:17 load avg: 0.82 [236/403/1] test_openpty
0:03:17 load avg: 0.82 [237/403/1] test_operator
0:03:17 load avg: 0.82 [238/403/1] test_optparse
0:03:18 load avg: 0.82 [239/403/1] test_ordered_dict
0:03:18 load avg: 0.82 [240/403/1] test_os
0:03:19 load avg: 0.82 [241/403/1] test_ossaudiodev
test_ossaudiodev skipped -- Use of the `audio' resource not enabled
0:03:19 load avg: 0.82 [242/403/1] test_parser -- test_ossaudiodev skipped (resource denied)
0:03:19 load avg: 0.82 [243/403/1] test_pdb
0:03:19 load avg: 0.82 [244/403/1] test_peepholer
0:03:19 load avg: 0.82 [245/403/1] test_pep247
0:03:19 load avg: 0.82 [246/403/1] test_pep277
test_pep277 skipped -- only NT+ and systems with Unicode-friendly filesystem encoding
0:03:19 load avg: 0.82 [247/403/1] test_pep352 -- test_pep277 skipped
0:03:19 load avg: 0.82 [248/403/1] test_pickle
0:03:22 load avg: 0.83 [249/403/1] test_pickletools
0:03:23 load avg: 0.83 [250/403/1] test_pipes
0:03:23 load avg: 0.83 [251/403/1] test_pkg
0:03:23 load avg: 0.83 [252/403/1] test_pkgimport
0:03:23 load avg: 0.83 [253/403/1] test_pkgutil
0:03:23 load avg: 0.83 [254/403/1] test_platform
0:03:23 load avg: 0.83 [255/403/1] test_plistlib
0:03:23 load avg: 0.83 [256/403/1] test_poll
0:03:34 load avg: 0.86 [257/403/1] test_popen
0:03:35 load avg: 0.86 [258/403/1] test_popen2
0:03:35 load avg: 0.86 [259/403/1] test_poplib
0:03:39 load avg: 0.79 [260/403/1] test_posix
test test_posix failed -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/test/test_posix.py", line 283, in test_makedev
    self.assertGreaterEqual(minor, 0)
AssertionError: -2030043135 not greater than or equal to 0

0:03:39 load avg: 0.79 [261/403/2] test_posixpath -- test_posix failed
0:03:39 load avg: 0.79 [262/403/2] test_pow
0:03:39 load avg: 0.79 [263/403/2] test_pprint
0:03:40 load avg: 0.79 [264/403/2] test_print
0:03:40 load avg: 0.79 [265/403/2] test_profile
0:03:40 load avg: 0.79 [266/403/2] test_property
0:03:40 load avg: 0.79 [267/403/2] test_pstats
0:03:40 load avg: 0.79 [268/403/2] test_pty
0:03:40 load avg: 0.79 [269/403/2] test_pwd
0:03:40 load avg: 0.79 [270/403/2] test_py3kwarn
test_py3kwarn skipped -- test.test_py3kwarn must be run with the -3 flag
0:03:40 load avg: 0.79 [271/403/2] test_py_compile -- test_py3kwarn skipped
0:03:40 load avg: 0.79 [272/403/2] test_pyclbr
0:03:41 load avg: 0.79 [273/403/2] test_pydoc
0:03:42 load avg: 0.80 [274/403/2] test_pyexpat
0:03:42 load avg: 0.80 [275/403/2] test_queue
0:03:46 load avg: 0.80 [276/403/2] test_quopri
0:03:46 load avg: 0.80 [277/403/2] test_random
0:03:47 load avg: 0.74 [278/403/2] test_re
0:03:48 load avg: 0.74 [279/403/2] test_readline
0:03:48 load avg: 0.74 [280/403/2] test_regrtest
0:03:50 load avg: 0.76 [281/403/2] test_repr
0:03:51 load avg: 0.76 [282/403/2] test_resource
0:03:51 load avg: 0.76 [283/403/2] test_rfc822
0:03:51 load avg: 0.76 [284/403/2] test_richcmp
0:03:51 load avg: 0.76 [285/403/2] test_rlcompleter
0:03:51 load avg: 0.76 [286/403/2] test_robotparser
0:03:51 load avg: 0.76 [287/403/2] test_runpy
0:03:54 load avg: 0.76 [288/403/2] test_sax
0:03:54 load avg: 0.76 [289/403/2] test_scope
0:03:54 load avg: 0.76 [290/403/2] test_scriptpackages
test_scriptpackages skipped -- No module named aetools
0:03:54 load avg: 0.76 [291/403/2] test_select -- test_scriptpackages skipped
0:04:06 load avg: 0.64 [292/403/2] test_set
0:04:07 load avg: 0.75 [293/403/2] test_setcomps
0:04:07 load avg: 0.75 [294/403/2] test_sets
0:04:07 load avg: 0.75 [295/403/2] test_sgmllib
0:04:07 load avg: 0.75 [296/403/2] test_sha
0:04:07 load avg: 0.75 [297/403/2] test_shelve
0:04:07 load avg: 0.75 [298/403/2] test_shlex
0:04:07 load avg: 0.75 [299/403/2] test_shutil
0:04:07 load avg: 0.75 [300/403/2] test_signal
0:04:15 load avg: 0.72 [301/403/2] test_site
0:04:15 load avg: 0.72 [302/403/2] test_slice
0:04:15 load avg: 0.72 [303/403/2] test_smtplib
0:04:16 load avg: 0.72 [304/403/2] test_smtpnet
test_smtpnet skipped -- Use of the `network' resource not enabled
0:04:16 load avg: 0.72 [305/403/2] test_socket -- test_smtpnet skipped (resource denied)
0:04:32 load avg: 0.56 [306/403/2] test_socketserver
test_socketserver skipped -- Use of the `network' resource not enabled
0:04:32 load avg: 0.56 [307/403/2] test_softspace -- test_socketserver skipped (resource denied)
0:04:32 load avg: 0.56 [308/403/2] test_sort
0:04:32 load avg: 0.56 [309/403/2] test_source_encoding
0:04:32 load avg: 0.56 [310/403/2] test_spwd
test_spwd skipped -- No module named spwd
0:04:33 load avg: 0.56 [311/403/2] test_sqlite -- test_spwd skipped
0:04:33 load avg: 0.56 [312/403/2] test_ssl
test test_ssl failed -- Traceback (most recent call last):
  File "/usr/local/lib/python2.7/test/test_ssl.py", line 1005, in test_load_dh_params
    shutil.copy(DHFILE, fname)
  File "/usr/local/lib/python2.7/shutil.py", line 131, in copy
    if os.path.isdir(dst):
  File "/usr/local/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 18: ordinal not in range(128)

0:04:34 load avg: 0.56 [313/403/3] test_startfile -- test_ssl failed
test_startfile skipped -- module 'os' has no attribute 'startfile'
0:04:35 load avg: 0.56 [314/403/3] test_stat -- test_startfile skipped
0:04:35 load avg: 0.56 [315/403/3] test_str
0:04:36 load avg: 0.59 [316/403/3] test_strftime
0:04:37 load avg: 0.59 [317/403/3] test_string
0:04:38 load avg: 0.59 [318/403/3] test_stringprep
0:04:38 load avg: 0.59 [319/403/3] test_strop
0:04:38 load avg: 0.59 [320/403/3] test_strptime
0:04:38 load avg: 0.59 [321/403/3] test_strtod
0:04:39 load avg: 0.59 [322/403/3] test_struct
0:04:40 load avg: 0.62 [323/403/3] test_structmembers
0:04:40 load avg: 0.62 [324/403/3] test_structseq
0:04:41 load avg: 0.62 [325/403/3] test_subprocess
0:05:46 load avg: 0.93 [326/403/3] test_sunau -- test_subprocess passed in 1 min 5 sec
0:05:46 load avg: 0.93 [327/403/3] test_sunaudiodev
test_sunaudiodev skipped -- No module named sunaudiodev
0:05:46 load avg: 0.93 [328/403/3] test_sundry -- test_sunaudiodev skipped
0:05:46 load avg: 0.93 [329/403/3] test_symtable
0:05:46 load avg: 0.93 [330/403/3] test_syntax
0:05:46 load avg: 0.93 [331/403/3] test_sys
0:05:47 load avg: 0.93 [332/403/3] test_sys_setprofile
0:05:47 load avg: 0.93 [333/403/3] test_sys_settrace
0:05:47 load avg: 0.93 [334/403/3] test_sysconfig
0:05:47 load avg: 0.93 [335/403/3] test_tarfile
0:05:49 load avg: 0.93 [336/403/3] test_tcl
0:05:49 load avg: 0.93 [337/403/3] test_telnetlib
0:05:54 load avg: 0.86 [338/403/3] test_tempfile
0:05:55 load avg: 0.86 [339/403/3] test_test_support
0:05:55 load avg: 0.86 [340/403/3] test_textwrap
0:05:55 load avg: 0.86 [341/403/3] test_thread
0:05:55 load avg: 0.86 [342/403/3] test_threaded_import
0:05:55 load avg: 0.86 [343/403/3] test_threadedtempfile
0:05:56 load avg: 0.86 [344/403/3] test_threading
0:05:59 load avg: 0.79 [345/403/3] test_threading_local
0:06:00 load avg: 0.79 [346/403/3] test_threadsignals
0:06:00 load avg: 0.79 [347/403/3] test_time
0:06:01 load avg: 0.79 [348/403/3] test_timeit
0:06:02 load avg: 0.79 [349/403/3] test_timeout
test_timeout skipped -- Use of the `network' resource not enabled
0:06:02 load avg: 0.89 [350/403/3] test_tk -- test_timeout skipped (resource denied)
test_tk skipped -- Use of the `gui' resource not enabled
0:06:02 load avg: 0.89 [351/403/3] test_tokenize -- test_tk skipped (resource denied)
0:06:02 load avg: 0.89 [352/403/3] test_tools
test_tools skipped -- test irrelevant for an installed Python
0:06:02 load avg: 0.89 [353/403/3] test_trace -- test_tools skipped
0:06:04 load avg: 0.89 [354/403/3] test_traceback
0:06:08 load avg: 0.81 [355/403/3] test_transformer
0:06:08 load avg: 0.81 [356/403/3] test_ttk_guionly
test_ttk_guionly skipped -- Use of the `gui' resource not enabled
0:06:09 load avg: 0.81 [357/403/3] test_ttk_textonly -- test_ttk_guionly skipped (resource denied)
0:06:09 load avg: 0.81 [358/403/3] test_tuple
0:06:16 load avg: 0.83 [359/403/3] test_turtle
0:06:16 load avg: 0.83 [360/403/3] test_typechecks
0:06:16 load avg: 0.83 [361/403/3] test_ucn
0:06:16 load avg: 0.83 [362/403/3] test_unary
0:06:16 load avg: 0.83 [363/403/3] test_undocumented_details
0:06:17 load avg: 0.83 [364/403/3] test_unicode
0:06:33 load avg: 0.88 [365/403/3] test_unicode_file
test_unicode_file skipped -- No Unicode filesystem semantics on this platform.
0:06:33 load avg: 0.88 [366/403/3] test_unicodedata -- test_unicode_file skipped
0:06:37 load avg: 0.88 [367/403/3] test_univnewlines
0:06:37 load avg: 0.88 [368/403/3] test_univnewlines2k
0:06:37 load avg: 0.88 [369/403/3] test_unpack
0:06:37 load avg: 0.88 [370/403/3] test_urllib
0:06:37 load avg: 0.88 [371/403/3] test_urllib2
0:06:37 load avg: 0.88 [372/403/3] test_urllib2_localnet
0:06:39 load avg: 0.81 [373/403/3] test_urllib2net
test_urllib2net skipped -- Use of the `network' resource not enabled
0:06:39 load avg: 0.81 [374/403/3] test_urllibnet -- test_urllib2net skipped (resource denied)
test_urllibnet skipped -- Use of the `network' resource not enabled
0:06:39 load avg: 0.81 [375/403/3] test_urlparse -- test_urllibnet skipped (resource denied)
0:06:39 load avg: 0.81 [376/403/3] test_userdict
0:06:40 load avg: 0.81 [377/403/3] test_userlist
0:06:41 load avg: 0.81 [378/403/3] test_userstring
0:06:45 load avg: 0.82 [379/403/3] test_uu
0:06:45 load avg: 0.82 [380/403/3] test_uuid
0:06:45 load avg: 0.82 [381/403/3] test_wait3
0:06:51 load avg: 0.84 [382/403/3] test_wait4
0:06:56 load avg: 0.85 [383/403/3] test_warnings
0:06:57 load avg: 0.85 [384/403/3] test_wave
0:06:57 load avg: 0.85 [385/403/3] test_weakref
0:07:11 load avg: 1.03 [386/403/3] test_weakset
0:07:12 load avg: 1.03 [387/403/3] test_whichdb
0:07:12 load avg: 1.03 [388/403/3] test_winreg
test_winreg skipped -- No module named _winreg
0:07:12 load avg: 1.03 [389/403/3] test_winsound -- test_winreg skipped
test_winsound skipped -- Use of the `audio' resource not enabled
0:07:12 load avg: 1.03 [390/403/3] test_with -- test_winsound skipped (resource denied)
0:07:12 load avg: 1.03 [391/403/3] test_wsgiref
0:07:12 load avg: 1.03 [392/403/3] test_xdrlib
0:07:12 load avg: 1.03 [393/403/3] test_xml_etree
0:07:13 load avg: 1.03 [394/403/3] test_xml_etree_c
0:07:13 load avg: 1.03 [395/403/3] test_xmllib
0:07:13 load avg: 1.03 [396/403/3] test_xmlrpc
0:07:16 load avg: 1.03 [397/403/3] test_xpickle
0:07:17 load avg: 1.03 [398/403/3] test_xrange
0:07:17 load avg: 1.03 [399/403/3] test_zipfile
0:07:20 load avg: 1.03 [400/403/3] test_zipfile64
test_zipfile64 skipped -- test requires loads of disk-space bytes and a long time to run
0:07:21 load avg: 1.03 [401/403/3] test_zipimport -- test_zipfile64 skipped (resource denied)
0:07:21 load avg: 1.03 [402/403/3] test_zipimport_support
0:07:21 load avg: 1.03 [403/403/3] test_zlib
357 tests OK.
3 tests failed:
    test_multiprocessing test_posix test_ssl
43 tests skipped:
    test_aepack test_al test_applesingle test_bsddb test_bsddb3
    test_cd test_cl test_codecmaps_cn test_codecmaps_hk
    test_codecmaps_jp test_codecmaps_kr test_codecmaps_tw test_curses
    test_dl test_epoll test_gdb test_gdbm test_gl test_imageop
    test_imgfile test_linuxaudiodev test_macos test_macostools
    test_msilib test_ossaudiodev test_pep277 test_py3kwarn
    test_scriptpackages test_smtpnet test_socketserver test_spwd
    test_startfile test_sunaudiodev test_timeout test_tk test_tools
    test_ttk_guionly test_unicode_file test_urllib2net test_urllibnet
    test_winreg test_winsound test_zipfile64
Ask someone to teach regrtest.py about which tests are
expected to get skipped on freebsd11.

Total duration: 7 min 24 sec
Tests result: FAILURE
```

**Comment by yurivict** [comment]
Version 0.13.2
