### ISSUE TITLE
Cannot install in Mac Catalina 

### ISSUE THREAD

**Issue by bolerap** [ludbb/secp256k1-py#34]
hi al.
I am trying to install this lib but got failed on Mac Catalina 
this is error log i got. Can you take a look. 

```
2019-12-28T15:35:26,718 Collecting secp256k1
2019-12-28T15:35:26,718   Created temporary directory: /private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-unpack-8b97l6sg
2019-12-28T15:35:26,782   Using cached https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz
2019-12-28T15:35:26,842   Added secp256k1 from https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#sha256=a3b43e02d321c09eafa769a6fc2c156f555cab3a7db62175ef2fd21e16cdf20c to build tracker '/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-req-tracker-andiakrd'
2019-12-28T15:35:26,847     Running setup.py (path:/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-install-asprpmg1/secp256k1/setup.py) egg_info for package secp256k1
2019-12-28T15:35:26,847     Running command python setup.py egg_info
2019-12-28T15:35:27,126     0.29.2
2019-12-28T15:35:27,147     WARNING: The wheel package is not available.
2019-12-28T15:35:28,680       ERROR: Command errored out with exit status 1:
2019-12-28T15:35:28,681        command: /Users/antory/.pyenv/versions/3.6.9/envs/p36env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-wheel-y2eg77wj/pytest-runner/setup.py'"'"'; __file__='"'"'/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-wheel-y2eg77wj/pytest-runner/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-wheel-cwga1twi
2019-12-28T15:35:28,681            cwd: /private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-wheel-y2eg77wj/pytest-runner/
2019-12-28T15:35:28,681       Complete output (7 lines):
2019-12-28T15:35:28,681       WARNING: The wheel package is not available.
2019-12-28T15:35:28,681       usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
2019-12-28T15:35:28,681          or: setup.py --help [cmd1 cmd2 ...]
2019-12-28T15:35:28,681          or: setup.py --help-commands
2019-12-28T15:35:28,681          or: setup.py cmd --help

2019-12-28T15:35:28,681       error: invalid command 'bdist_wheel'
2019-12-28T15:35:28,681       ----------------------------------------
2019-12-28T15:35:28,681       ERROR: Failed building wheel for pytest-runner
2019-12-28T15:35:28,903     ERROR: Failed to build one or more wheels
2019-12-28T15:35:28,948     Traceback (most recent call last):
2019-12-28T15:35:28,948       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
2019-12-28T15:35:28,949         subprocess.check_call(cmd)
2019-12-28T15:35:28,949       File "/Users/antory/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 311, in check_call
2019-12-28T15:35:28,949         raise CalledProcessError(retcode, cmd)
2019-12-28T15:35:28,949     subprocess.CalledProcessError: Command '['/Users/antory/.pyenv/versions/3.6.9/envs/p36env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/tmpkysqesjx', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.

2019-12-28T15:35:28,949     During handling of the above exception, another exception occurred:

2019-12-28T15:35:28,949     Traceback (most recent call last):
2019-12-28T15:35:28,949       File "<string>", line 1, in <module>
2019-12-28T15:35:28,949       File "/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-install-asprpmg1/secp256k1/setup.py", line 295, in <module>
2019-12-28T15:35:28,949         "Topic :: Security :: Cryptography"
2019-12-28T15:35:28,949       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
2019-12-28T15:35:28,949         _install_setup_requires(attrs)
2019-12-28T15:35:28,949       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
2019-12-28T15:35:28,949         dist.fetch_build_eggs(dist.setup_requires)
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
2019-12-28T15:35:28,950         replace_conflicting=True,
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
2019-12-28T15:35:28,950         replace_conflicting=replace_conflicting
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
2019-12-28T15:35:28,950         return self.obtain(req, installer)
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
2019-12-28T15:35:28,950         return installer(requirement)
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
2019-12-28T15:35:28,950         return fetch_build_egg(self, req)
2019-12-28T15:35:28,950       File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
2019-12-28T15:35:28,950         raise DistutilsError(str(e))
2019-12-28T15:35:28,950     distutils.errors.DistutilsError: Command '['/Users/antory/.pyenv/versions/3.6.9/envs/p36env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/tmpkysqesjx', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
2019-12-28T15:35:28,969 Cleaning up...
2019-12-28T15:35:28,970   Removing source in /private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-install-asprpmg1/secp256k1
2019-12-28T15:35:28,983 Removed secp256k1 from https://files.pythonhosted.org/packages/52/62/d7bf3829e126e517e253d2e22a63511c54bbaac34d7ddea316cde040fc49/secp256k1-0.13.2.tar.gz#sha256=a3b43e02d321c09eafa769a6fc2c156f555cab3a7db62175ef2fd21e16cdf20c from build tracker '/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-req-tracker-andiakrd'
2019-12-28T15:35:28,983 Removed build tracker '/private/var/folders/md/xlm2b58s5wv6sm85x0rdz_w80000gn/T/pip-req-tracker-andiakrd'
2019-12-28T15:35:28,983 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2019-12-28T15:35:28,983 Exception information:
2019-12-28T15:35:28,983 Traceback (most recent call last):
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
2019-12-28T15:35:28,983     status = self.run(options, args)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
2019-12-28T15:35:28,983     resolver.resolve(requirement_set)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
2019-12-28T15:35:28,983     self._resolve_one(requirement_set, req)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
2019-12-28T15:35:28,983     abstract_dist = self._get_abstract_dist_for(req_to_install)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
2019-12-28T15:35:28,983     req, self.session, self.finder, self.require_hashes
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
2019-12-28T15:35:28,983     req, self.req_tracker, finder, self.build_isolation,
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
2019-12-28T15:35:28,983     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
2019-12-28T15:35:28,983     self.req.prepare_metadata()
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
2019-12-28T15:35:28,983     self.metadata_directory = metadata_generator(self)
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
2019-12-28T15:35:28,983     command_desc='python setup.py egg_info',
2019-12-28T15:35:28,983   File "/Users/antory/.pyenv/versions/3.6.9/envs/p36env/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2019-12-28T15:35:28,983     raise InstallationError(exc_msg)
2019-12-28T15:35:28,983 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by N3TC4T** [comment]
`pip install wheel`
